# Auto-generated by TestRunner._try_regenerate_test_index() during editor runs.
# Do not edit manually -- changes will be overwritten.
# This file is checked in so exported builds can discover test suites.

const SUITES := [
	"res://tests/test_cad_workflows.gd",
	"res://tests/test_select_iter.gd",
]
