class_name TestObstacles

const OK := 0
const OBSTACLES_DIR := "res://ball_game/scripts/components/obstacles"

const POSITIVE_MIN_VOL_RATIO := 0.5
const POSITIVE_MAX_VOL_RATIO := 0.9
const NEGATIVE_MIN_VOL_RATIO := 0.1
const NEGATIVE_MAX_VOL_RATIO := 0.5

static func _init_runtime() -> int:
	var s = OclCore.runtime_init()
	if s != OK and s != 2:
		return s
	return OK

static func _get_obstacle_filter() -> String:
	return OS.get_environment("OBSTACLE_FILTER")

static func _discover_obstacles() -> Array[Dictionary]:
	var filter := _get_obstacle_filter()
	var result: Array[Dictionary] = []

	# Try DirAccess first (works in editor) — regenerates index for exports.
	var dir := DirAccess.open(OBSTACLES_DIR)
	if dir != null:
		dir.list_dir_begin()
		while true:
			var fname := dir.get_next()
			if fname == "":
				break
			if dir.current_is_dir():
				continue
			if not fname.begins_with("obstacle_") or not fname.ends_with(".gd"):
				continue
			if fname == "obstacle_base.gd" or fname == "obstacle_index.gd":
				continue
			if filter != "" and not fname.get_basename().contains(filter):
				continue
			var path := "%s/%s" % [OBSTACLES_DIR, fname]
			var script := load(path)
			if script == null:
				continue
			if script is Script and script.has_method("build"):
				result.append({"name": fname.get_basename(), "path": path, "script": script})
		dir.list_dir_end()
		result.sort_custom(func(a, b): return a["name"] < b["name"])
		_write_obstacle_index(result)
		return result

	# Fallback: ObstacleIndex (exported builds).
	result = ObstacleIndex.get_all(filter)
	return result


const INDEX_HEADER := """# WARNING: Auto-generated by TestObstacles._discover_obstacles().
# Do not edit manually. Regenerated each test run.

"""

static func _write_obstacle_index(obstacles: Array[Dictionary]) -> void:
	var path := "%s/obstacle_index.gd" % OBSTACLES_DIR
	var lines := PackedStringArray([INDEX_HEADER])
	lines.append('class_name ObstacleIndex')
	lines.append('extends RefCounted')
	lines.append('')
	lines.append('const PATH := "%s"' % OBSTACLES_DIR)
	lines.append('')
	lines.append('const OBSTACLES: Array[Dictionary] = [')
	for obs in obstacles:
		lines.append('\t{"name": "%s", "path": "%s"},' % [obs["name"], obs["path"]])
	lines.append(']')
	lines.append('')
	lines.append('static func get_all(filter: String = "") -> Array[Dictionary]:')
	lines.append('\tvar result: Array[Dictionary] = []')
	lines.append('\tfor entry in OBSTACLES:')
	lines.append('\t\tif filter != "" and not entry["name"].contains(filter):')
	lines.append('\t\t\tcontinue')
	lines.append('\t\tvar script := load(entry["path"])')
	lines.append('\t\tif script is Script and script.has_method("build"):')
	lines.append('\t\t\tresult.append({"name": entry["name"], "path": entry["path"], "script": script})')
	lines.append('\treturn result')
	lines.append('')

	var f := FileAccess.open(path, FileAccess.WRITE)
	if f == null:
		return
	f.store_string("\n".join(lines))

static func _make_aabbs() -> Array[AABB]:
	return [
		AABB(Vector3(-8, -4, -4), Vector3(16, 8, 8)),
		AABB(Vector3(-4, -8, -4), Vector3(8, 16, 8)),
		AABB(Vector3(-4, -4, -8), Vector3(8, 8, 16)),
	]

static func _make_transforms() -> Array[Transform3D]:
	return [
		Transform3D.IDENTITY,
		Transform3D(Basis(Vector3(1, 0, 0), deg_to_rad(45)), Vector3(2, 3, 1)),
		Transform3D(Basis(Vector3(1, 1, 1).normalized(), deg_to_rad(37)), Vector3(-1, 2, -3)),
	]

static func _get_volume(graph: OclGraphHandle, root_bits: int) -> float:
	var props := OclGraphMassProperties.new()
	var s = OclTopoBuild.graph_mass_properties_get(graph, root_bits, props)
	if s != OK:
		return -1.0
	return props.get_volume()

static func _check_volume(graph: OclGraphHandle, root_bits: int, aabb: AABB, is_positive: bool) -> String:
	var vol := _get_volume(graph, root_bits)
	if vol <= 0:
		return ""
	var aabb_vol := aabb.size.x * aabb.size.y * aabb.size.z
	if aabb_vol <= 0:
		return "degenerate aabb"
	var ratio := vol / aabb_vol
	if ratio < 0.01:
		return ""
	if is_positive:
		if ratio < POSITIVE_MIN_VOL_RATIO:
			return "vol too low: %.1f%% (need >%.0f%%)" % [ratio * 100, POSITIVE_MIN_VOL_RATIO * 100]
		if ratio > POSITIVE_MAX_VOL_RATIO:
			return "vol too high: %.1f%% (need <%.0f%%)" % [ratio * 100, POSITIVE_MAX_VOL_RATIO * 100]
	else:
		if ratio < NEGATIVE_MIN_VOL_RATIO:
			return "neg vol too low: %.1f%% (need >%.0f%%)" % [ratio * 100, NEGATIVE_MIN_VOL_RATIO * 100]
		if ratio > NEGATIVE_MAX_VOL_RATIO:
			return "neg vol too high: %.1f%% (need <%.0f%%)" % [ratio * 100, NEGATIVE_MAX_VOL_RATIO * 100]
	return ""

static func _build_obstacle(script: Script, graph: OclGraphHandle, aabb: AABB, xf: Transform3D) -> PackedInt64Array:
	var raw = script.build(graph, aabb, xf)
	if raw is PackedInt64Array:
		return raw
	if raw is int:
		return PackedInt64Array([raw]) if raw > 0 else PackedInt64Array()
	return PackedInt64Array()

static func _get_coarse_mesh_opts() -> OclMeshOptions:
	var opts := OclMeshOptions.new()
	opts.set_deflection(0.1)
	opts.set_angle(4.0)
	return opts

static func _build_obstacle_and_mesh(script: Script, aabb: AABB, xf: Transform3D) -> Dictionary:
	var graph := OclGraphHandle.new()
	if OclTopo.graph_create(graph) != OK:
		return {"error": "graph_create failed"}

	var roots := _build_obstacle(script, graph, aabb, xf)
	if roots.is_empty():
		return {"error": "build returned no roots"}

	var mesh := ArrayMesh.new()
	var mesh_result = OclMeshToGodot.mesh_faces(graph, mesh, _get_coarse_mesh_opts())
	if mesh_result != OK:
		return {"error": "mesh_faces failed: %d" % mesh_result}

	return {"graph": graph, "root": roots[0], "mesh": mesh}

static func _build_obstacle_and_cut(script: Script, aabb: AABB, xf: Transform3D) -> Dictionary:
	var graph := OclGraphHandle.new()
	if OclTopo.graph_create(graph) != OK:
		return {"error": "graph_create failed"}

	var roots := _build_obstacle(script, graph, aabb, xf)
	if roots.is_empty():
		return {"error": "build returned no roots"}

	var cutter_bits := roots[0]

	var base_info := OclPrimBoxInfo.new()
	base_info.set_dx(aabb.size.x)
	base_info.set_dy(aabb.size.y)
	base_info.set_dz(aabb.size.z)
	var base := OclNodeId.new()
	if OclPrimSolid.box(graph, base_info, base) != OK:
		return {"error": "base box failed"}

	var out := OclNodeId.new()
	var s = OclBool.cut(
		graph,
		PackedInt64Array([base.get_bits()]),
		PackedInt64Array([cutter_bits]),
		OclBoolOptions.new(),
		out,
	)
	if s != OK:
		OclTopo.graph_free(graph)
		return {"skipped": "bool cut not applicable: %d" % s}

	return {"graph": graph, "root": out.get_bits(), "mesh": null}

static func _export_stl(graph: OclGraphHandle, root_bits: int, path: String) -> String:
	var opts := OclIoStlWriteOptions.new()
	opts.ascii_mode = 0
	var status = OclIoStl.write(graph, root_bits, path, opts)
	if status != OK:
		return "STL write to %s failed: %s - %s" % [path, OclCore.status_to_string(status), var_to_str(OclCore.error_last())]
	return ""

static func test_obstacle_count() -> String:
	var obstacles := _discover_obstacles()
	if obstacles.is_empty():
		return "no obstacles discovered in %s" % OBSTACLES_DIR
	if obstacles.size() < 3:
		var names := PackedStringArray()
		for o in obstacles:
			names.append(o["name"])
		return "expected at least 10 obstacles, found %d: %s" % [obstacles.size(), ", ".join(names)]
	return "OK"

static func _fmt_key(obs_name: String, aabb: AABB, xf_i: int) -> String:
	return "%s[%dx%dx%d,t%d]" % [obs_name, int(aabb.size.x), int(aabb.size.y), int(aabb.size.z), xf_i]

static func test_build_all_obstacles() -> String:
	var init_err := _init_runtime()
	if init_err != OK:
		return "runtime_init failed: %d" % init_err

	var obstacles := _discover_obstacles()
	if obstacles.is_empty():
		return "no obstacles discovered"

	var aabbs := _make_aabbs()
	var transforms := _make_transforms()
	var errors := PackedStringArray()
	var built := 0
	var total_us := 0

	for obs in obstacles:
		var obs_start := Time.get_ticks_usec()
		var obs_errors := 0
		for aabb in aabbs:
			for xf_i in range(transforms.size()):
				var xf: Transform3D = transforms[xf_i]
				var key := _fmt_key(obs["name"], aabb, xf_i)
				var result := _build_obstacle_and_mesh(obs["script"], aabb, xf)
				if result.has("error"):
					errors.append("%s: %s" % [key, result["error"]])
					obs_errors += 1
					continue

				var vol_err := _check_volume(result["graph"], result["root"], aabb, true)
				if vol_err != "":
					errors.append("%s vol: %s" % [key, vol_err])

				OclTopo.graph_free(result["graph"])
				built += 1
		var obs_us := Time.get_ticks_usec() - obs_start
		total_us += obs_us
		print("  [obs] %s: %d builds, %d errors, %.1f ms" % [obs["name"], 9 - obs_errors, obs_errors, obs_us / 1000.0])

	print("  [obs] Total: %d builds, %.1f s" % [built, total_us / 1000000.0])

	if errors.size() > 0:
		return "%d/%d builds failed:\n%s" % [errors.size(), built + errors.size(), "\n".join(errors)]
	return "OK"

static func test_mesh_all_obstacles() -> String:
	var init_err := _init_runtime()
	if init_err != OK:
		return "runtime_init failed: %d" % init_err

	var obstacles := _discover_obstacles()
	if obstacles.is_empty():
		return "no obstacles discovered"

	var aabbs := _make_aabbs()
	var transforms := _make_transforms()
	var stl_dir := OS.get_environment("OBSTACLE_STL_EXPORT_DIR")
	var errors := PackedStringArray()
	var meshed := 0

	for obs in obstacles:
		for aabb in aabbs:
			for xf_i in range(transforms.size()):
				var xf: Transform3D = transforms[xf_i]
				var key := _fmt_key(obs["name"], aabb, xf_i)
				var result := _build_obstacle_and_mesh(obs["script"], aabb, xf)
				if result.has("error"):
					errors.append("%s: %s" % [key, result["error"]])
					continue

				if stl_dir != "":
					DirAccess.make_dir_recursive_absolute(stl_dir)
					var stl_path := "%s/%s.stl" % [stl_dir, key.replace("[", "_").replace("]", "").replace("x", "x")]
					var stl_err := _export_stl(result["graph"], result["root"], stl_path)
					if stl_err != "":
						errors.append("%s stl: %s" % [key, stl_err])

				OclTopo.graph_free(result["graph"])
				meshed += 1

	if errors.size() > 0:
		return "%d/%d meshes failed:\n%s" % [errors.size(), meshed + errors.size(), "\n".join(errors)]
	return "OK"

static func test_cut_all_obstacles() -> String:
	var init_err := _init_runtime()
	if init_err != OK:
		return "runtime_init failed: %d" % init_err

	var obstacles := _discover_obstacles()
	if obstacles.is_empty():
		return "no obstacles discovered"

	var aabbs := _make_aabbs()
	var transforms := _make_transforms()
	var stl_dir := OS.get_environment("OBSTACLE_STL_EXPORT_DIR")
	var errors := PackedStringArray()
	var cut := 0
	var working_negatives := PackedStringArray()

	for obs in obstacles:
		for aabb in aabbs:
			for xf_i in range(transforms.size()):
				var xf: Transform3D = transforms[xf_i]
				var key := _fmt_key(obs["name"], aabb, xf_i)
				var result := _build_obstacle_and_cut(obs["script"], aabb, xf)
				if result.has("skipped"):
					continue
				if result.has("error"):
					errors.append("%s: %s" % [key, result["error"]])
					continue

				if stl_dir != "":
					var mesh := ArrayMesh.new()
					var mesh_res = OclMeshToGodot.mesh_faces(result["graph"], mesh, _get_coarse_mesh_opts())
					if mesh_res != OK:
						errors.append("%s stl_mesh: %d" % [key, mesh_res])
					else:
						DirAccess.make_dir_recursive_absolute(stl_dir)
						var stl_path := "%s/%s_neg.stl" % [stl_dir, key.replace("[", "_").replace("]", "").replace("x", "x")]
						var stl_err := _export_stl(result["graph"], result["root"], stl_path)
						if stl_err != "":
							errors.append("%s stl: %s" % [key, stl_err])

				OclTopo.graph_free(result["graph"])
				cut += 1
				working_negatives.append(obs["name"])

	if errors.size() > 0:
		return "%d/%d cuts failed:\n%s" % [errors.size(), cut + errors.size(), "\n".join(errors)]

	_write_negative_index(working_negatives)
	return "OK"

static func _write_negative_index(names: PackedStringArray) -> void:
	var unique: Dictionary = {}
	for n in names:
		unique[n] = true
	var sorted_names := Array(unique.keys())
	sorted_names.sort()

	var path := "user://negative_obstacle_index.txt"
	var file := FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		return
	for n in sorted_names:
		file.store_line(n)
	file.close()
