class_name TestOclGodotMesher

# ---------------------------------------------------------------------------
# This file was auto-generated by the OCCT-Light.gd-autowrapper.
# DO NOT EDIT IT DIRECTLY. Make changes to the Python generator instead.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

static func v3_to_p3(v3: Vector3) -> OclPoint3:
	var p3 := OclPoint3.new()
	p3.x = v3.x
	p3.y = v3.y
	p3.z = v3.z
	return p3

static func v3_to_d3(v3: Vector3) -> OclDirection3:
	var p3 := OclDirection3.new()
	p3.x = v3.x
	p3.y = v3.y
	p3.z = v3.z
	return p3

static func _collect_node_kind_ids(graph, kind: int) -> Array:
	var ids := []
	var out_iter := OclNodeIterHandle.new()
	var status: int
	match kind:
		OclCore.KIND_SOLID:
			status = OclTopo.graph_solid_iter_create(graph, out_iter)
		OclCore.KIND_SHELL:
			status = OclTopo.graph_shell_iter_create(graph, out_iter)
		OclCore.KIND_FACE:
			status = OclTopo.graph_face_iter_create(graph, out_iter)
		OclCore.KIND_WIRE:
			status = OclTopo.graph_wire_iter_create(graph, out_iter)
		OclCore.KIND_EDGE:
			status = OclTopo.graph_edge_iter_create(graph, out_iter)
		OclCore.KIND_VERTEX:
			status = OclTopo.graph_vertex_iter_create(graph, out_iter)
		OclCore.KIND_COMPOUND:
			status = OclTopo.graph_compound_iter_create(graph, out_iter)
		OclCore.KIND_COMPSOLID:
			status = OclTopo.graph_compsolid_iter_create(graph, out_iter)
		OclCore.KIND_COEDGE:
			status = OclTopo.graph_coedge_iter_create(graph, out_iter)
		_:
			return []
	if status != 0 or out_iter == null:
		return []
	var out_id = OclNodeId.new()
	while true:
		status = OclTopo.node_iter_next(out_iter, out_id)
		if status != 0:
			break
		ids.append(out_id.get_bits())
	return ids

static func _make_box_graph() -> Dictionary:
	var rt_status = OclCore.runtime_init()
	# INVALID_ARGUMENT (2) = runtime already initialized — not a fatal error
	if rt_status != 0 and rt_status != 2:
		return {"error": "runtime_init failed: %d" % rt_status}

	var graph := OclGraphHandle.new()
	var create_err := OclTopo.graph_create(graph)
	if create_err != 0 or graph == null:
		return {"error": "graph_create failed: err=%d" % create_err}

	var info = OclPrimBoxInfo.new()
	info.set_dx(10.0)
	info.set_dy(20.0)
	info.set_dz(30.0)

	var box_root = OclNodeId.new()
	var status = OclPrimSolid.box(graph, info, box_root)
	if status != 0:
		return {"error": "make_box failed: %d" % status}

	return {"graph": graph, "root": box_root}

static func _make_advanced_pipe_graph() -> Dictionary:
	var rt_status = OclCore.runtime_init()
	if rt_status != 0 and rt_status != 2:
		return {"error": "runtime_init failed: %d" % rt_status}

	var graph := OclGraphHandle.new()
	var create_err := OclTopo.graph_create(graph)
	if create_err != 0 or graph == null:
		return {"error": "graph_create failed: err=%d" % create_err}

	# Spline control points (avoid Godot Path3D/Curve3D which would leak)
	var ctrl_points := [
		Vector3(-12.0, 0.0, 0.0),
		Vector3(-6.0, 3.0, 2.0),
		Vector3(0.0, 0.0, 6.0),
		Vector3(8.0, -2.0, 10.0),
		Vector3(14.0, 1.0, 14.0),
	]

	var spline_info := OclPrimSplineInfo.new()
	spline_info.points = OclPoint3Array.from(ctrl_points.map(func(p): return v3_to_p3(p)))
	var spline_wire_id := OclNodeId.new()
	var status = OclPrimSketch.spline(graph, spline_info, spline_wire_id) as OclCore.status
	if status != OclCore.OK:
		return {"error": "spline failed: %s" % OclCore.status_to_string(status)}

	var plane_info := OclPrimPlaneInfo.new()
	plane_info.width = 8.0
	plane_info.height = 3.2
	var plane_info_placement := OclAxis2Placement.new()
	plane_info_placement.x_dir = v3_to_d3(-Vector3(0, 0, 1))
	plane_info_placement.x_dir_ref = v3_to_d3(-Vector3(1, 0, 0))
	# The spline starts at the first control point when the curve passes
	# through all points (OCCT BSpline interpolation)
	plane_info_placement.location = v3_to_p3(ctrl_points[0])
	plane_info.placement = plane_info_placement
	var plane_face_id := OclNodeId.new()
	status = OclPrimSketch.plane(graph, plane_info, plane_face_id) as OclCore.status
	if status != OclCore.OK:
		return {"error": "plane failed: %s" % OclCore.status_to_string(status)}

	var sweep_info := OclPrimPipeInfo.new()
	sweep_info.spine_wire = spline_wire_id.bits
	sweep_info.profile = plane_face_id.bits
	var sweep_id := OclNodeId.new()
	status = OclPrimSweep.pipe(graph, sweep_info, sweep_id) as OclCore.status
	if status != OclCore.OK:
		return {"error": "pipe failed: %s" % OclCore.status_to_string(status)}

	return {"graph": graph, "root": sweep_id}

static func _triangle_normal_sum_from_nodes(nodes: PackedFloat64Array, triangles: PackedInt32Array) -> Vector3:
	var sum := Vector3.ZERO
	for i in range(0, triangles.size(), 3):
		var i0 := triangles[i]
		var i1 := triangles[i + 1]
		var i2 := triangles[i + 2]
		var a := Vector3(nodes[i0 * 3], nodes[i0 * 3 + 1], nodes[i0 * 3 + 2])
		var b := Vector3(nodes[i1 * 3], nodes[i1 * 3 + 1], nodes[i1 * 3 + 2])
		var c := Vector3(nodes[i2 * 3], nodes[i2 * 3 + 1], nodes[i2 * 3 + 2])
		var n := (b - a).cross(c - a)
		if n.length_squared() > 1e-30:
			sum += n.normalized()
	return sum

static func _triangle_normal_sum_from_verts(verts: PackedVector3Array, triangles: PackedInt32Array) -> Vector3:
	var sum := Vector3.ZERO
	for i in range(0, triangles.size(), 3):
		var a := verts[triangles[i]]
		var b := verts[triangles[i + 1]]
		var c := verts[triangles[i + 2]]
		var n := (b - a).cross(c - a)
		if n.length_squared() > 1e-30:
			sum += n.normalized()
	return sum

# ---------------------------------------------------------------------------
# Mesh batch methods — edge cases (null/invalid graph)
# ---------------------------------------------------------------------------

static func test_mesh_faces_null_graph() -> String:
	var graph = OclGraphHandle.new()
	# Graph handle is null — should return empty ArrayMesh
	var mesh = OclGodotMesher.mesh_faces(graph)
	if mesh == null:
		return "expected non-null ArrayMesh, got null"
	if mesh.get_surface_count() != 0:
		return "expected 0 surfaces for null graph, got %d" % mesh.get_surface_count()
	return "OK"

static func test_mesh_faces_reuse_existing() -> String:
	var graph = OclGraphHandle.new()
	var existing = ArrayMesh.new()
	# Add a dummy surface to verify it gets cleared
	var dummy_arr = []
	dummy_arr.resize(Mesh.ARRAY_MAX)
	var verts = PackedVector3Array([Vector3(0,0,0), Vector3(1,0,0), Vector3(0,1,0)])
	dummy_arr[Mesh.ARRAY_VERTEX] = verts
	var idxs = PackedInt32Array([0, 1, 2])
	dummy_arr[Mesh.ARRAY_INDEX] = idxs
	existing.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, dummy_arr)
	if existing.get_surface_count() != 1:
		return "expected 1 dummy surface before reuse"

	var result = OclGodotMesher.mesh_faces(graph, existing, null, [])
	if result != existing:
		return "expected same ArrayMesh object back"
	# Should be cleared (no surfaces due to empty face_ids)
	if result.get_surface_count() != 0:
		return "expected 0 surfaces after clear with no ids, got %d" % result.get_surface_count()
	return "OK"

static func test_mesh_edges_null_graph() -> String:
	var graph = OclGraphHandle.new()
	var mm = OclGodotMesher.mesh_edges(graph)
	if mm == null:
		return "expected non-null MultiMesh, got null"
	if mm.get_instance_count() != 0:
		return "expected 0 instances for null graph, got %d" % mm.get_instance_count()
	return "OK"

static func test_mesh_edges_reuse_existing() -> String:
	var graph = OclGraphHandle.new()
	var mm = MultiMesh.new()
	mm.set_instance_count(5)
	var result = OclGodotMesher.mesh_edges(graph, mm, null, [])
	if result != mm:
		return "expected same MultiMesh object back"
	if result.get_instance_count() != 0:
		return "expected 0 instances after clear"
	return "OK"

static func test_mesh_vertices_null_graph() -> String:
	var graph = OclGraphHandle.new()
	var mm = OclGodotMesher.mesh_vertices(graph)
	if mm == null:
		return "expected non-null MultiMesh, got null"
	if mm.get_instance_count() != 0:
		return "expected 0 instances for null graph, got %d" % mm.get_instance_count()
	return "OK"

static func test_mesh_vertices_reuse_existing() -> String:
	var graph = OclGraphHandle.new()
	var mm = MultiMesh.new()
	mm.set_instance_count(5)
	var result = OclGodotMesher.mesh_vertices(graph, mm, null, [])
	if result != mm:
		return "expected same MultiMesh object back"
	if result.get_instance_count() != 0:
		return "expected 0 instances after clear"
	return "OK"

# ---------------------------------------------------------------------------
# Mesh batch methods — integration tests
# Creates a box solid, then tests faces/edges/vertices meshing
# ---------------------------------------------------------------------------

static func test_mesh_faces_with_box() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OclGraphHandle = result.graph

	# Test with all attributes enabled and explicit mesh options
	var mesh_opts = OclMeshOptions.new()
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = OclMesh.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var face_ids = _collect_node_kind_ids(graph, OclCore.KIND_FACE)
	if face_ids.size() == 0:
		return "no faces found in box graph"

	var mesh = OclGodotMesher.mesh_faces(graph, null, mesh_opts,
		PackedInt64Array(face_ids), true, true, true, true)
	if mesh == null:
		return "mesh_faces returned null"
	if mesh.get_surface_count() == 0:
		return "expected at least 1 surface, got 0"

	var surface_arrays = mesh.surface_get_arrays(0)
	if surface_arrays.size() <= Mesh.ARRAY_VERTEX:
		return "surface arrays too small"
	var verts = surface_arrays[Mesh.ARRAY_VERTEX] as PackedVector3Array
	if verts.size() == 0:
		return "expected non-empty vertex array"

	var has_normals = surface_arrays[Mesh.ARRAY_NORMAL] != null
	var has_uvs = surface_arrays[Mesh.ARRAY_TEX_UV] != null
	var has_tangents = surface_arrays[Mesh.ARRAY_TANGENT] != null
	var has_colors = surface_arrays[Mesh.ARRAY_COLOR] != null

	if not has_normals:
		return "expected normals (include_normals=true)"
	if not has_uvs:
		return "expected UVs (include_uvs=true)"
	if not has_tangents:
		return "expected tangents (include_tangents=true)"
	if not has_colors:
		return "expected feature ID colors (include_feature_ids=true)"

	return "OK"

static func test_mesh_faces_winding_matches_triangulation_on_advanced_pipe() -> String:
	var result = _make_advanced_pipe_graph()
	if result.has("error"):
		return result.error

	var graph: OclGraphHandle = result.graph

	var mesh_opts = OclMeshOptions.new()
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = OclMesh.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var face_ids = _collect_node_kind_ids(graph, OclCore.KIND_FACE)
	if face_ids.size() == 0:
		return "no faces found in pipe graph"

	var chosen_face: int = -1
	var source_tri := OclTriangulationView.new()
	var source_nodes: PackedFloat64Array
	var source_triangles: PackedInt32Array
	for face_id in face_ids:
		source_tri = OclTriangulationView.new()
		var tri_status := OclMesh.face_triangulation(graph, face_id, source_tri)
		if tri_status == 0 and source_tri.nodes.size() != 0 and source_tri.triangles.size() != 0:
			chosen_face = face_id
			# Eagerly copy triangulation data while OCCT cache pointers are still valid.
			# mesh_faces() below may regenerate the mesh and invalidate borrowed pointers.
			source_nodes = source_tri.nodes
			source_triangles = source_tri.triangles
			break
	if chosen_face < 0:
		return "no triangulated face found on advanced pipe"

	var mesh = OclGodotMesher.mesh_faces(graph, null, mesh_opts,
		PackedInt64Array([chosen_face]), true, true, true, true)
	if mesh == null:
		return "mesh_faces returned null"
	if mesh.get_surface_count() != 1:
		return "expected a single surface for one face, got %d" % mesh.get_surface_count()

	var surface_arrays = mesh.surface_get_arrays(0)
	var verts = surface_arrays[Mesh.ARRAY_VERTEX] as PackedVector3Array
	var normals = surface_arrays[Mesh.ARRAY_NORMAL] as PackedVector3Array
	var indices = surface_arrays[Mesh.ARRAY_INDEX] as PackedInt32Array
	if verts.size() == 0:
		return "expected non-empty vertex array"
	if normals.size() == 0:
		return "expected non-empty normals array"
	if indices.size() == 0:
		return "expected non-empty index array"

	# Compare geometric normals from source triangulation winding and mesh_faces winding.
	# The OCCT-Light layer already adjusts REVERSED faces so that the triangulation
	# always has CCW winding (as seen from outside).  mesh_faces must preserve this
	# winding — the geometric face normal computed from both should agree.
	var source_normal := _triangle_normal_sum_from_nodes(source_nodes, source_triangles)
	if source_normal.length_squared() < 0.1:
		return "OCCT triangulation has degenerate geometry (all zero-area triangles)"

	var mesh_normal := _triangle_normal_sum_from_verts(verts, indices)
	if mesh_normal.length_squared() < 0.1:
		return "mesh_faces produced degenerate geometry (all zero-area triangles)"

	var dot := source_normal.dot(mesh_normal)
	if dot <= 0.0:
		return "expected Godot mesh face normal (%s) to point in same direction as OCCT triangulation normal (%s), got dot=%f" % [mesh_normal, source_normal, dot]

	return "OK"

# Compute the face normal from OCCT per-vertex normals (true surface orientation).
static func _triangle_normal_sum_from_nodes_and_normals(nodes: PackedFloat64Array, normals: PackedFloat64Array, triangles: PackedInt32Array) -> Vector3:
	if normals.size() == 0:
		return Vector3.ZERO
	var sum := Vector3.ZERO
	for i in range(0, triangles.size(), 3):
		var i0 := triangles[i]
		var i1 := triangles[i + 1]
		var i2 := triangles[i + 2]
		var n0 := Vector3(normals[i0 * 3], normals[i0 * 3 + 1], normals[i0 * 3 + 2])
		var n1 := Vector3(normals[i1 * 3], normals[i1 * 3 + 1], normals[i1 * 3 + 2])
		var n2 := Vector3(normals[i2 * 3], normals[i2 * 3 + 1], normals[i2 * 3 + 2])
		var avg := (n0 + n1 + n2) / 3.0
		if avg.length_squared() > 1e-30:
			sum += avg.normalized()
	if sum.length_squared() > 1e-30:
		return sum.normalized()
	return Vector3.ZERO

static func test_mesh_faces_defaults_no_attributes() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OclGraphHandle = result.graph

	var mesh_opts = OclMeshOptions.new()
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = OclMesh.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var face_ids = _collect_node_kind_ids(graph, OclCore.KIND_FACE)
	if face_ids.size() == 0:
		return "no faces found in box graph"

	# All attributes disabled by default for performance
	var mesh = OclGodotMesher.mesh_faces(graph, null, null, PackedInt64Array(face_ids))
	if mesh == null:
		return "mesh_faces returned null"
	if mesh.get_surface_count() == 0:
		return "expected at least 1 surface, got 0"

	var surface_arrays = mesh.surface_get_arrays(0)
	var has_normals = surface_arrays[Mesh.ARRAY_NORMAL] != null
	var has_uvs = surface_arrays[Mesh.ARRAY_TEX_UV] != null
	var has_tangents = surface_arrays[Mesh.ARRAY_TANGENT] != null

	if has_normals:
		return "expected NO normals by default"
	if has_uvs:
		return "expected NO UVs by default"
	if has_tangents:
		return "expected NO tangents by default"

	return "OK"

static func test_mesh_edges_with_box() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OclGraphHandle = result.graph

	var mesh_opts = OclMeshOptions.new()
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = OclMesh.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var edge_ids = _collect_node_kind_ids(graph, OclCore.KIND_EDGE)
	if edge_ids.size() == 0:
		return "no edges found in box graph"

	var mm = OclGodotMesher.mesh_edges(graph, null, mesh_opts,
		PackedInt64Array(edge_ids), 0.5)
	if mm == null:
		return "mesh_edges returned null"
	if mm.get_instance_count() == 0:
		return "expected at least 1 instance, got 0"
	if mm.get_mesh() == null:
		return "expected a base cylinder mesh"

	return "OK"

static func test_mesh_vertices_with_box() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OclGraphHandle = result.graph

	var mesh_opts = OclMeshOptions.new()
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = OclMesh.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var vert_ids = _collect_node_kind_ids(graph, OclCore.KIND_VERTEX)
	if vert_ids.size() == 0:
		return "no vertices found in box graph"

	var mm = OclGodotMesher.mesh_vertices(graph, null, mesh_opts,
		PackedInt64Array(vert_ids), 0.02)
	if mm == null:
		return "mesh_vertices returned null"
	if mm.get_instance_count() == 0:
		return "expected at least 1 instance, got 0"
	if mm.get_mesh() == null:
		return "expected a base sphere mesh"

	return "OK"

# ---------------------------------------------------------------------------
# Bounding-box consistency: mesh_edges and mesh_vertices should use the
# graph-wide bbox via _get_graph_bbox_diag for consistent sizing.
# ---------------------------------------------------------------------------

static func test_mesh_bbox_consistency() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OclGraphHandle = result.graph

	var mesh_opts = OclMeshOptions.new()
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = OclMesh.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var edge_ids = _collect_node_kind_ids(graph, OclCore.KIND_EDGE)
	var vert_ids = _collect_node_kind_ids(graph, OclCore.KIND_VERTEX)

	if edge_ids.size() == 0:
		return "no edges found"

	var edge_mm = OclGodotMesher.mesh_edges(graph, null, mesh_opts,
		PackedInt64Array(edge_ids), 0.01)
	if edge_mm == null:
		return "mesh_edges returned null"
	if edge_mm.get_instance_count() == 0:
		return "expected edge instances"

	if vert_ids.size() == 0:
		return "no vertices found"

	var vert_mm = OclGodotMesher.mesh_vertices(graph, null, mesh_opts,
		PackedInt64Array(vert_ids), 0.02)
	if vert_mm == null:
		return "mesh_vertices returned null"
	if vert_mm.get_instance_count() == 0:
		return "expected vertex instances"

	return "OK"

# ---------------------------------------------------------------------------
# PhysicsBody3D collision shape tests
# ---------------------------------------------------------------------------

static func test_mesh_faces_physics_body() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OclGraphHandle = result.graph

	var mesh_opts = OclMeshOptions.new()
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = OclMesh.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var face_ids = _collect_node_kind_ids(graph, OclCore.KIND_FACE)
	if face_ids.size() == 0:
		return "no faces found"

	var body = StaticBody3D.new()
	var ret = OclGodotMesher.mesh_faces(graph, body, mesh_opts,
		PackedInt64Array(face_ids), false, false, false, false)
	if ret != null:
		return "expected null return when passing PhysicsBody3D, got %s" % ret

	if body.get_child_count() == 0:
		return "expected at least 1 CollisionShape3D child"
	var cs = body.get_child(0) as CollisionShape3D
	if cs == null:
		return "expected CollisionShape3D children"
	var meta = cs.get_meta("occtl") as Dictionary
	if meta == null or not meta.has("feature_id"):
		return "expected occtl metadata with feature_id"
	var shape = cs.get_shape()
	if shape == null:
		return "expected shape on CollisionShape3D"
	if not (shape is ConcavePolygonShape3D):
		return "expected ConcavePolygonShape3D for faces, got %s" % shape.get_class()
	body.free()
	return "OK"

static func test_mesh_edges_physics_body() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OclGraphHandle = result.graph

	var mesh_opts = OclMeshOptions.new()
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = OclMesh.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var edge_ids = _collect_node_kind_ids(graph, OclCore.KIND_EDGE)
	if edge_ids.size() == 0:
		return "no edges found"

	var body = StaticBody3D.new()
	var ret = OclGodotMesher.mesh_edges(graph, body, mesh_opts,
		PackedInt64Array(edge_ids), 0.01)
	if ret != null:
		return "expected null return when passing PhysicsBody3D"
	if body.get_child_count() == 0:
		return "expected at least 1 CollisionShape3D child"
	var cs = body.get_child(0) as CollisionShape3D
	if cs == null:
		return "expected CollisionShape3D children"
	var meta = cs.get_meta("occtl") as Dictionary
	if meta == null or not meta.has("feature_id"):
		return "expected occtl metadata with feature_id"
	var shape = cs.get_shape()
	if shape == null:
		return "expected shape on CollisionShape3D"
	if not (shape is CapsuleShape3D):
		return "expected CapsuleShape3D for edges, got %s" % shape.get_class()
	body.free()
	return "OK"

static func test_mesh_vertices_physics_body() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OclGraphHandle = result.graph

	var mesh_opts = OclMeshOptions.new()
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = OclMesh.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var vert_ids = _collect_node_kind_ids(graph, OclCore.KIND_VERTEX)
	if vert_ids.size() == 0:
		return "no vertices found"

	var body = StaticBody3D.new()
	var ret = OclGodotMesher.mesh_vertices(graph, body, mesh_opts,
		PackedInt64Array(vert_ids), 0.02)
	if ret != null:
		return "expected null return when passing PhysicsBody3D"
	if body.get_child_count() == 0:
		return "expected at least 1 CollisionShape3D child"
	var cs = body.get_child(0) as CollisionShape3D
	if cs == null:
		return "expected CollisionShape3D children"
	var meta = cs.get_meta("occtl") as Dictionary
	if meta == null or not meta.has("feature_id"):
		return "expected occtl metadata with feature_id"
	var shape = cs.get_shape()
	if shape == null:
		return "expected shape on CollisionShape3D"
	if not (shape is SphereShape3D):
		return "expected SphereShape3D for vertices, got %s" % shape.get_class()
	body.free()
	return "OK"

static func test_physics_body_reuse_clears_children() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OclGraphHandle = result.graph

	var mesh_opts = OclMeshOptions.new()
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = OclMesh.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var edge_ids = _collect_node_kind_ids(graph, OclCore.KIND_EDGE)
	if edge_ids.size() == 0:
		return "no edges found"

	var body = StaticBody3D.new()
	# First call adds collision children
	OclGodotMesher.mesh_edges(graph, body, mesh_opts, PackedInt64Array(edge_ids), 0.01)
	var first_count = body.get_child_count()
	if first_count == 0:
		return "expected children after first call"

	# Second call with same body should clear previous children and re-add
	OclGodotMesher.mesh_edges(graph, body, mesh_opts, PackedInt64Array(edge_ids), 0.01)
	var second_count = body.get_child_count()
	if second_count != first_count:
		return "expected same number of children after reuse, got %d vs %d" % [second_count, first_count]

	body.free()
	return "OK"
