@tool
class_name MeshExportUtils
extends RefCounted

## Static utility methods for exporting Godot mesh data to common file formats.
##
## Supports binary STL and Wavefront OBJ export from ArrayMesh data.
## All methods are static and pure — no state, no scene dependencies.

# -----------------------------------------------------------------------------
# Binary STL
# -----------------------------------------------------------------------------

## Write a binary STL file from vertex/index data.
## |triangles| is a PackedVector3Array of vertex positions (3n elements,
## where each consecutive triple forms a triangle).
static func write_stl(path: String, triangles: PackedVector3Array, solid_name: String = "maze_track") -> Error:
	var file := FileAccess.open(path, FileAccess.WRITE)
	if not file:
		return FileAccess.get_open_error()

	# 80-byte header.
	var header := solid_name.lpad(80, "\x00").left(80).to_ascii_buffer()
	if header.size() < 80:
		header.resize(80)
	file.store_buffer(header.slice(0, 80))

	# 4-byte triangle count.
	var tri_count := triangles.size() / 3
	file.store_32(tri_count)

	# Each triangle: 12 bytes normal + 36 bytes vertices + 2 bytes attribute.
	var i := 0
	while i < triangles.size():
		var v0 := triangles[i]
		var v1 := triangles[i + 1]
		var v2 := triangles[i + 2]
		var normal := Plane(v0, v1, v2).normal

		file.store_float(normal.x)
		file.store_float(normal.y)
		file.store_float(normal.z)

		file.store_float(v0.x); file.store_float(v0.y); file.store_float(v0.z)
		file.store_float(v1.x); file.store_float(v1.y); file.store_float(v1.z)
		file.store_float(v2.x); file.store_float(v2.y); file.store_float(v2.z)

		file.store_16(0)  # attribute byte count
		i += 3

	return OK


## Extract all triangle vertices from an ArrayMesh into a flat
## PackedVector3Array (3 vertices per triangle, triangles are NOT indexed).
static func mesh_to_triangles(mesh: ArrayMesh) -> PackedVector3Array:
	var out := PackedVector3Array()
	for surf_idx in mesh.get_surface_count():
		var arrays := mesh.surface_get_arrays(surf_idx)
		var verts: PackedVector3Array = arrays[Mesh.ARRAY_VERTEX]
		var indices: PackedInt32Array

		if arrays.size() > Mesh.ARRAY_INDEX and arrays[Mesh.ARRAY_INDEX] != null:
			indices = arrays[Mesh.ARRAY_INDEX]
			for idx in range(0, indices.size(), 3):
				out.append(verts[indices[idx]])
				out.append(verts[indices[idx + 1]])
				out.append(verts[indices[idx + 2]])
		else:
			# Non-indexed — every 3 vertices is one triangle.
			out.append_array(verts)

	return out


## Write an ArrayMesh to binary STL.
static func write_mesh_stl(path: String, mesh: ArrayMesh, solid_name: String = "maze_track") -> Error:
	var tris := mesh_to_triangles(mesh)
	if tris.is_empty():
		return ERR_INVALID_DATA
	return write_stl(path, tris, solid_name)


# -----------------------------------------------------------------------------
# Wavefront OBJ
# -----------------------------------------------------------------------------

## Write an ArrayMesh to a Wavefront OBJ file (one object per surface).
static func write_mesh_obj(path: String, mesh: ArrayMesh, object_name: String = "maze_track") -> Error:
	var file := FileAccess.open(path, FileAccess.WRITE)
	if not file:
		return FileAccess.get_open_error()

	file.store_line("# Generated by OCCT-Light.gd TrackExporter")
	file.store_line("o " + object_name)

	var base_vtx := 1
	for surf_idx in mesh.get_surface_count():
		var arrays := mesh.surface_get_arrays(surf_idx)
		var verts: PackedVector3Array = arrays[Mesh.ARRAY_VERTEX]
		var norms: PackedVector3Array = arrays[Mesh.ARRAY_NORMAL] if arrays.size() > Mesh.ARRAY_NORMAL and arrays[Mesh.ARRAY_NORMAL] != null else PackedVector3Array()

		# Vertices.
		for v in verts:
			file.store_line("v %.6f %.6f %.6f" % [v.x, v.y, v.z])

		# Normals.
		for n in norms:
			file.store_line("vn %.6f %.6f %.6f" % [n.x, n.y, n.z])

		# Faces.
		var indices: PackedInt32Array
		if arrays.size() > Mesh.ARRAY_INDEX and arrays[Mesh.ARRAY_INDEX] != null:
			indices = arrays[Mesh.ARRAY_INDEX]
		else:
			indices.resize(verts.size())
			for j in range(verts.size()):
				indices[j] = j

		var has_normals := norms.size() == verts.size()
		for j in range(0, indices.size(), 3):
			var a := base_vtx + indices[j]
			var b := base_vtx + indices[j + 1]
			var c := base_vtx + indices[j + 2]
			if has_normals:
				file.store_line("f %d//%d %d//%d %d//%d" % [a, a, b, b, c, c])
			else:
				file.store_line("f %d %d %d" % [a, b, c])

		base_vtx += verts.size()

	return OK
