# WARNING: Auto-generated by TestObstacles._discover_obstacles().
# Do not edit manually. Regenerated each test run.


class_name ObstacleIndex
extends RefCounted

const PATH := "res://ball_game/scripts/components/obstacles"

const OBSTACLES: Array[Dictionary] = [
	{"name": "obstacle_box", "path": "res://ball_game/scripts/components/obstacles/obstacle_box.gd"},
	{"name": "obstacle_check_topology", "path": "res://ball_game/scripts/components/obstacles/obstacle_check_topology.gd"},
	{"name": "obstacle_column", "path": "res://ball_game/scripts/components/obstacles/obstacle_column.gd"},
	{"name": "obstacle_common_intersection", "path": "res://ball_game/scripts/components/obstacles/obstacle_common_intersection.gd"},
	{"name": "obstacle_cone", "path": "res://ball_game/scripts/components/obstacles/obstacle_cone.gd"},
	{"name": "obstacle_cut_shape", "path": "res://ball_game/scripts/components/obstacles/obstacle_cut_shape.gd"},
	{"name": "obstacle_cylinder", "path": "res://ball_game/scripts/components/obstacles/obstacle_cylinder.gd"},
	{"name": "obstacle_ellipse_prism", "path": "res://ball_game/scripts/components/obstacles/obstacle_ellipse_prism.gd"},
	{"name": "obstacle_fused_pair", "path": "res://ball_game/scripts/components/obstacles/obstacle_fused_pair.gd"},
	{"name": "obstacle_half_cylinder", "path": "res://ball_game/scripts/components/obstacles/obstacle_half_cylinder.gd"},
	{"name": "obstacle_halfspace_slice", "path": "res://ball_game/scripts/components/obstacles/obstacle_halfspace_slice.gd"},
	{"name": "obstacle_offset_shape", "path": "res://ball_game/scripts/components/obstacles/obstacle_offset_shape.gd"},
	{"name": "obstacle_prism_hexagon", "path": "res://ball_game/scripts/components/obstacles/obstacle_prism_hexagon.gd"},
	{"name": "obstacle_revolve_half", "path": "res://ball_game/scripts/components/obstacles/obstacle_revolve_half.gd"},
	{"name": "obstacle_sphere", "path": "res://ball_game/scripts/components/obstacles/obstacle_sphere.gd"},
	{"name": "obstacle_torus", "path": "res://ball_game/scripts/components/obstacles/obstacle_torus.gd"},
	{"name": "obstacle_tube", "path": "res://ball_game/scripts/components/obstacles/obstacle_tube.gd"},
	{"name": "obstacle_wedge", "path": "res://ball_game/scripts/components/obstacles/obstacle_wedge.gd"},
]

static func get_all(filter: String = "") -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	for entry in OBSTACLES:
		if filter != "" and not entry["name"].contains(filter):
			continue
		var script := load(entry["path"])
		if script is Script and script.has_method("build"):
			result.append({"name": entry["name"], "path": entry["path"], "script": script})
	return result
