#ifndef OCL_TOPO_EXTRA_H
#define OCL_TOPO_EXTRA_H

#include <godot_cpp/classes/resource.hpp>
#include <godot_cpp/core/class_db.hpp>
#include "autowrapper/OclGraphHandle.h"
#include "autowrapper/OclInt32.h"

using namespace godot;

/// Hand-written topology utilities not generated by the autowrapper.
/// Exposed as a separate GDScript class OclTopoExtra.
class OclTopoExtra : public godot::Resource {
    GDCLASS(OclTopoExtra, godot::Resource)
protected:
    static void _bind_methods();
public:
    /// Returns 1 in out_result when any face pair of the solid has a bounded
    /// section edge with arc-length >= min_edge_length.  0 = clean solid.
    static int solid_is_self_intersecting(
        const Ref<OclGraphHandle>& graph,
        int64_t solid,
        double min_edge_length,
        const Ref<OclInt32>& out_result);
};

#endif // OCL_TOPO_EXTRA_H
